# Generated by Django 4.2.7 on 2023-12-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_han', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textimg',
            name='text',
            field=models.TextField(blank=True, max_length='200', null=True),
        ),
    ]
