# Generated by Django 4.2.7 on 2023-12-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_han', '0002_textimg_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.TextField(max_length='100')),
                ('tran_text', models.TextField(max_length='2000')),
            ],
        ),
    ]
