# Generated by Django 4.2.7 on 2023-12-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_han', '0003_tran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_text', models.TextField(max_length='2000')),
                ('voice_lang', models.TextField(max_length='200')),
                ('tran_texte', models.TextField(max_length='2000')),
                ('tran_voice', models.FileField(upload_to='tran_voice')),
            ],
        ),
    ]
