# Generated by Django 4.2.7 on 2023-12-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_han', '0004_voic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voicesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_text', models.TextField(max_length='2000')),
                ('voice_lang', models.TextField(max_length='200')),
                ('voice_tran_lang', models.TextField(blank=True, max_length='200', null=True)),
                ('tran_texte', models.TextField(max_length='2000')),
                ('tran_voice', models.FileField(upload_to='tran_voice')),
            ],
        ),
        migrations.AddField(
            model_name='voic',
            name='voice_tran_lang',
            field=models.TextField(blank=True, max_length='200', null=True),
        ),
    ]
