# Generated by Django 4.2.7 on 2023-12-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_han', '0005_voicesk_voic_voice_tran_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicesk',
            name='voice_tran_lang',
            field=models.TextField(max_length='200'),
        ),
    ]
