# Generated by Django 4.2.7 on 2023-12-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_han', '0007_alter_voicesk_tran_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicesk',
            name='tran_voice',
            field=models.FileField(upload_to='text_photo'),
        ),
    ]
